### ISSUE TITLE
前台启动完后，调用服务器后台，非鉴权部分的url提示401，获取用户request.getCookies()分支报错。前台提示跨域

### ISSUE THREAD

**Issue by lyb-1108** [moyangzhan/aideepin-web#2]
前台启动完后，调用服务器后台，非鉴权部分的url提示401，获取用户request.getCookies()分支报错。前台提示跨域

**Comment by moyangzhan** [comment]
跨域问题使用nginx来解决，具体的配置可以参考：https://github.com/moyangzhan/langchain4j-aideepin-web/blob/main/docker-compose/nginx/nginx.conf
